version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(pip)"
    groups:
      api-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "tensorflow"
      - dependency-name: "numpy"
      - dependency-name: "opencv-python"
    reviewers:
      - "ninepiece2"

  - package-ecosystem: "npm"
    directory: "/UI"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(npm)"
    groups:
      ui-dependencies:
        patterns:
          - "*"
    reviewers:
      - "ninepiece2"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(github-actions)"
    groups:
      github-actions:
        patterns:
          - "*"
    reviewers:
      - "ninepiece2"
