version: '3.8'

services:
  api:
    image: ninepiece2/mri-brain-tumor-detection:api
    container_name: MRI-Brain-Tumor-Detection-API
    ports:
      - "443:443"
    restart: always
  
  ui:
    image: ninepiece2/mri-brain-tumor-detection:ui
    container_name: MRI-Brain-Tumor-Detection-UI
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BASE_URL=https://api:443
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/certs:/etc/nginx/ssl:ro
    depends_on:
      - ui