name: Build API Docker CI

on:
  push:
    branches:
      - main
    paths:
      - API/**
      - Flask-Dockerfile
      - requirements.txt
      - Pipfile
      - Pipfile.lock
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Download Release Asset from Latest Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh release download --repo NinePiece2/MRI-Brain-Tumor-Detection --pattern "classification_model.h5" --pattern "segmentation_model.h5" --dir models

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Flask-Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mri-brain-tumor-detection:api
    
      - name: Trigger Deploy Workflow
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: build-completed